apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: satis
  annotations:
    github.com/project-slug: yourparkingspace/satis
spec:
  type: service
  lifecycle: production
  owner: marketplace-backend
